bot_token = "<YOUR_TELEGRAM_BOT_API_KEY>"
bot_user_name = "<YOUR_TELEGRAM_BOT_URL>"
URL = "<HTTPS_URL_OF_THE_SERVER_WHERE_YOUR_APP_WILL_BE_HOSTED>"
owner_username = "<YOUR_TELEGRAM_ACCOUNT_USERNAME>"
